### ISSUE TITLE
Move to deploy-on-release

### ISSUE THREAD

**Issue by surchs** [neurobagel/ui#106]
Like we learned with the annotation tool (https://github.com/neurobagel/annotation_tool/issues/790): deploying to prod from every main merge is risky. Let's not do that anymore.

Instead
- [x] Change our deployment process to only run on a release
- [ ] Find a way to have a running "nightly" version with a persistent name (i.e. not the staging previews, but maybe netlify works)
- [x] Setup / carry over the auto-release workflow from other projects

**Comment by rmanaem** [comment]
This tool currently doesn't have a release workflow. That needs to be added either as part of this issue or another issue to proceed.

**Comment by surchs** [comment]
The "nightly" builds are already happening and going to https://upload-ui.netlify.app/. So we can close the issue
